# Generated by Django 4.0.3 on 2023-01-13 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='NSFW',
            field=models.BooleanField(default=False),
        ),
    ]
