# Generated by Django 4.0.3 on 2022-05-21 21:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('name', models.CharField(blank=True,
                 max_length=200, primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('picture', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Topics',
            fields=[
                ('name', models.CharField(max_length=50,
                 primary_key=True, serialize=False)),
                ('room', models.ForeignKey(
                    null=True, on_delete=django.db.models.deletion.SET_NULL, to='room.room')),
            ],
        ),
        migrations.CreateModel(
            name='Followed',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('isAdmin', models.BooleanField()),
                ('room', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='room.room')),
                ('user', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(blank=True)),
                ('likes', models.IntegerField(default=0)),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('room', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='room.room')),
                ('user', models.ForeignKey(
                    null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('likes', models.IntegerField(default=0)),
                ('body', models.TextField(blank=True)),
                ('room', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='room.room')),
            ],
        ),
    ]
