# Generated by Django 4.0.3 on 2022-06-16 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followed',
            name='isAdmin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name='followed',
            constraint=models.UniqueConstraint(
                fields=('room', 'user'), name='unique_follow'),
        ),
    ]
