# Generated by Django 4.0.3 on 2023-04-03 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='followed',
            name='online',
            field=models.BooleanField(default=False),
        ),
    ]
