# Generated by Django 4.0.3 on 2023-04-06 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0003_followed_online'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='followed',
            name='online',
        ),
    ]
