# Generated by Django 4.0.3 on 2023-03-05 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0004_room_nsfw'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topics',
            name='room',
        ),
        migrations.AddField(
            model_name='room',
            name='topic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='room.topics'),
        ),
    ]
